# Generated by Django 5.1.2 on 2024-10-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduleapp', '0002_remove_judge_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='cabinet',
            field=models.IntegerField(default='22'),
            preserve_default=False,
        ),
    ]
