# Generated by Django 5.1.2 on 2024-10-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduleapp', '0003_judge_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='arbitration_court',
            field=models.CharField(default='2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judge',
            name='name',
            field=models.CharField(default='2', max_length=50),
            preserve_default=False,
        ),
    ]
