# Generated by Django 5.1.2 on 2024-10-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduleapp', '0004_judge_arbitration_court_judge_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbitration_court', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('day_name', models.CharField(max_length=100)),
                ('cabinet', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
