# Generated by Django 5.1.2 on 2024-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduleapp', '0007_judges_site_shedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judges',
            name='site_shedule',
        ),
        migrations.AddField(
            model_name='judges',
            name='url',
            field=models.URLField(default='https://schedule.arbitr.ru/Schedule/Operator/?courtTag=SPB&cabinetName=<django.db.models.fields.IntegerField>'),
        ),
    ]
