# Generated by Django 5.1.2 on 2024-10-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduleapp', '0008_remove_judges_site_shedule_judges_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='cabinet',
        ),
    ]
