# Generated by Django 5.1.2 on 2024-10-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduleapp', '0009_remove_site_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judges',
            name='url',
            field=models.URLField(),
        ),
    ]
